[profile.default]
solc_version = "0.8.19"

cache = true
cache_path = 'cache'
evm_version = 'london'

libs = ['lib']
names = false
offline = false
optimizer = true
optimizer_runs = 888888
out = 'out'
src = 'src'
test = 'test'
